// Countries a record was acquired in. Singapore, Japan, and USA are pinned right after
// "Select" since they're the most common for this collection; the rest follow alphabetically.
export const ACQUISITION_COUNTRIES: string[] = [
  "Singapore",
  "Japan",
  "USA",
  "Australia",
  "Austria",
  "Belgium",
  "Brazil",
  "Canada",
  "China",
  "Denmark",
  "Finland",
  "France",
  "Germany",
  "Hong Kong",
  "India",
  "Indonesia",
  "Ireland",
  "Italy",
  "Malaysia",
  "Mexico",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Philippines",
  "Poland",
  "Portugal",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "United Kingdom",
  "Vietnam",
  "Other",
];

// Order matters here — this is the exact order requested for the dropdown.
export const ACQUISITION_TRANSACTION_TYPES: string[] = [
  "Online Auction",
  "Online Store",
  "Online Marketplaces",
  "Thrift Store",
  "Record Store",
  "Garage Sales",
  "Free Gift",
];
